import { useState, useEffect } from "react";
import { Mic, Loader2, ChevronRight, Clock, RotateCcw, CheckCircle2 } from "lucide-react";
import { getTopics, getQuestions, submitInterview, getSessionHistory } from "../../api/interview.api";

const STAGES = { SETUP: "setup", ANSWERING: "answering", RESULTS: "results" };

function CircularScore({ value, size = 100, stroke = 9 }) {
  const radius = (size - stroke) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (value / 100) * circumference;
  const color = value >= 70 ? "#059669" : value >= 45 ? "var(--brand-600)" : "#dc2626";

  return (
    <svg width={size} height={size} style={{ transform: "rotate(-90deg)" }}>
      <circle cx={size / 2} cy={size / 2} r={radius} stroke="#eef1f7" strokeWidth={stroke} fill="none" />
      <circle
        cx={size / 2} cy={size / 2} r={radius} stroke={color} strokeWidth={stroke} fill="none"
        strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap="round"
        style={{ transition: "stroke-dashoffset 1s cubic-bezier(0.16,1,0.3,1)" }}
      />
      <text x="50%" y="50%" textAnchor="middle" dominantBaseline="central" transform={`rotate(90 ${size / 2} ${size / 2})`}
        style={{ fill: "var(--text-primary)", fontSize: size * 0.26, fontWeight: 700, fontFamily: "var(--font-heading)" }}>
        {value}
      </text>
    </svg>
  );
}

export default function MockInterview() {
  const [stage, setStage] = useState(STAGES.SETUP);
  const [topics, setTopics] = useState([]);
  const [interviewType, setInterviewType] = useState("hr");
  const [selectedTopic, setSelectedTopic] = useState("");
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);

  useEffect(() => {
    getTopics().then(setTopics).catch(() => {});
    getSessionHistory().then(setHistory).catch(() => {});
  }, []);

  const startInterview = async () => {
    setError("");
    setLoading(true);
    try {
      const qs = await getQuestions({ type: interviewType, topic: interviewType === "technical" ? selectedTopic : undefined, count: 5 });
      setQuestions(qs);
      setAnswers({});
      setStage(STAGES.ANSWERING);
    } catch (err) {
      setError(err.response?.data?.message || "Couldn't load questions. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async () => {
    setError("");
    setLoading(true);
    try {
      const payload = {
        interviewType,
        topic: interviewType === "technical" ? selectedTopic : "behavioral",
        answers: questions.map((q) => ({ questionId: q.id, answerText: answers[q.id] || "" })),
      };
      const session = await submitInterview(payload);
      setResult(session);
      setStage(STAGES.RESULTS);
      getSessionHistory().then(setHistory).catch(() => {});
    } catch (err) {
      setError(err.response?.data?.message || "Couldn't submit your interview. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const resetToSetup = () => {
    setStage(STAGES.SETUP);
    setQuestions([]);
    setAnswers({});
    setResult(null);
  };

  return (
    <div>
      <div style={{ marginBottom: 28 }}>
        <div style={{ width: 48, height: 48, borderRadius: 13, background: "linear-gradient(135deg, #eaf1fd, #dbe7fb)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--brand-600)", marginBottom: 16 }}>
          <Mic size={22} />
        </div>
        <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 6 }}>AI Mock Interviews</h1>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", maxWidth: 560, lineHeight: 1.6 }}>
          Practice HR and technical rounds with curated questions. Feedback is generated by rule-based
          checks — answer structure and keyword coverage for technical questions, STAR-method signals for
          HR questions — not a generative AI model.
        </p>
      </div>

      {error && (
        <p style={{ color: "#dc2626", fontSize: 13, marginBottom: 20, background: "#fef2f2", padding: "10px 14px", borderRadius: 10 }}>
          {error}
        </p>
      )}

      {stage === STAGES.SETUP && (
        <SetupView
          interviewType={interviewType}
          setInterviewType={setInterviewType}
          topics={topics}
          selectedTopic={selectedTopic}
          setSelectedTopic={setSelectedTopic}
          loading={loading}
          onStart={startInterview}
        />
      )}

      {stage === STAGES.ANSWERING && (
        <AnsweringView
          questions={questions}
          answers={answers}
          setAnswers={setAnswers}
          loading={loading}
          onSubmit={handleSubmit}
        />
      )}

      {stage === STAGES.RESULTS && result && (
        <ResultsView result={result} onRetry={resetToSetup} />
      )}

      {history.length > 0 && stage === STAGES.SETUP && (
        <div style={{ marginTop: 32 }}>
          <h2 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12, display: "flex", alignItems: "center", gap: 6 }}>
            <Clock size={15} color="var(--text-secondary)" /> Past interviews
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {history.map((h) => (
              <div key={h._id} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: "10px 14px" }}>
                <div>
                  <p style={{ fontSize: 12.5, fontWeight: 600, textTransform: "capitalize" }}>{h.interviewType} · {h.topic}</p>
                  <p style={{ fontSize: 11, color: "var(--text-muted)" }}>{new Date(h.createdAt).toLocaleDateString()}</p>
                </div>
                <span style={{ fontSize: 13, fontWeight: 700, color: h.overallScore >= 70 ? "#059669" : h.overallScore >= 45 ? "var(--brand-600)" : "#dc2626" }}>
                  {h.overallScore}/100
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function SetupView({ interviewType, setInterviewType, topics, selectedTopic, setSelectedTopic, loading, onStart }) {
  const canStart = interviewType === "hr" || (interviewType === "technical" && selectedTopic);

  return (
    <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 18, padding: 28, boxShadow: "var(--shadow-card)" }}>
      <p style={{ fontSize: 13, fontWeight: 600, marginBottom: 12 }}>Interview type</p>
      <div style={{ display: "flex", gap: 10, marginBottom: 20 }}>
        {["hr", "technical"].map((t) => (
          <button
            key={t}
            onClick={() => { setInterviewType(t); setSelectedTopic(""); }}
            style={{
              flex: 1, padding: "12px 0", borderRadius: 12, fontSize: 13.5, fontWeight: 600, textTransform: "capitalize",
              cursor: "pointer", border: interviewType === t ? "none" : "1px solid var(--border)",
              background: interviewType === t ? "var(--brand-gradient)" : "var(--surface)",
              color: interviewType === t ? "#fff" : "var(--text-secondary)",
            }}
          >
            {t === "hr" ? "HR / Behavioral" : "Technical"}
          </button>
        ))}
      </div>

      {interviewType === "technical" && (
        <>
          <p style={{ fontSize: 13, fontWeight: 600, marginBottom: 12 }}>Topic</p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 20 }}>
            {topics.map((t) => (
              <button
                key={t}
                onClick={() => setSelectedTopic(t)}
                style={{
                  padding: "8px 16px", borderRadius: 999, fontSize: 12.5, fontWeight: 600, textTransform: "capitalize",
                  cursor: "pointer", border: selectedTopic === t ? "none" : "1px solid var(--border)",
                  background: selectedTopic === t ? "#eaf1fd" : "var(--surface)",
                  color: selectedTopic === t ? "var(--brand-700)" : "var(--text-secondary)",
                }}
              >
                {t}
              </button>
            ))}
          </div>
        </>
      )}

      <button
        onClick={onStart}
        disabled={!canStart || loading}
        style={{
          display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
          width: "100%", background: "var(--brand-gradient)", color: "#fff", border: "none",
          borderRadius: 999, padding: "13px 0", fontSize: 14, fontWeight: 600,
          cursor: canStart ? "pointer" : "not-allowed", opacity: canStart ? 1 : 0.5,
          boxShadow: "0 10px 20px -8px rgba(37,99,235,0.5)",
        }}
      >
        {loading ? <Loader2 size={16} className="hf-spin" /> : <>Start interview <ChevronRight size={16} /></>}
      </button>
      <style>{`.hf-spin { animation: hf-spin-anim 0.8s linear infinite; } @keyframes hf-spin-anim { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}

function AnsweringView({ questions, answers, setAnswers, loading, onSubmit }) {
  const answeredCount = questions.filter((q) => (answers[q.id] || "").trim().length > 0).length;

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <p style={{ fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" }}>
          {answeredCount} of {questions.length} answered
        </p>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 16, marginBottom: 20 }}>
        {questions.map((q, i) => (
          <div key={q.id} style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 14, padding: 18 }}>
            <p style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 10 }}>
              {i + 1}. {q.question}
            </p>
            <textarea
              value={answers[q.id] || ""}
              onChange={(e) => setAnswers({ ...answers, [q.id]: e.target.value })}
              placeholder="Type your answer here..."
              rows={4}
              style={{
                width: "100%", background: "#f2f4f7", border: "1px solid transparent", borderRadius: 10,
                padding: "12px 14px", fontSize: 13.5, color: "var(--text-primary)", outline: "none",
                fontFamily: "var(--font-body)", resize: "vertical",
              }}
            />
          </div>
        ))}
      </div>
      <button
        onClick={onSubmit}
        disabled={loading}
        style={{
          display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
          width: "100%", background: "var(--brand-gradient)", color: "#fff", border: "none",
          borderRadius: 999, padding: "13px 0", fontSize: 14, fontWeight: 600, cursor: "pointer",
          boxShadow: "0 10px 20px -8px rgba(37,99,235,0.5)",
        }}
      >
        {loading ? "Evaluating..." : "Submit interview"}
      </button>
    </div>
  );
}

function ResultsView({ result, onRetry }) {
  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 24, flexWrap: "wrap", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 18, padding: 24, marginBottom: 20, boxShadow: "var(--shadow-card)" }}>
        <CircularScore value={result.overallScore} />
        <div style={{ flex: 1, minWidth: 200 }}>
          <p style={{ fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", marginBottom: 4 }}>Interview Score</p>
          <p style={{ fontSize: 12.5, color: "var(--text-muted)", textTransform: "capitalize" }}>{result.interviewType} · {result.topic}</p>
        </div>
        <button
          onClick={onRetry}
          style={{ display: "flex", alignItems: "center", gap: 6, background: "#eaf1fd", color: "var(--brand-700)", border: "1px solid #dbe7fb", borderRadius: 999, padding: "9px 16px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" }}
        >
          <RotateCcw size={14} /> Try another
        </button>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        {result.results.map((r, i) => (
          <div key={r.questionId} style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 14, padding: 18 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 10 }}>
              <p style={{ fontSize: 13.5, fontWeight: 600 }}>{i + 1}. {r.question}</p>
              <span style={{ fontSize: 13, fontWeight: 700, color: r.score >= 7 ? "#059669" : r.score >= 4 ? "var(--brand-600)" : "#dc2626", flexShrink: 0 }}>
                {r.score}/10
              </span>
            </div>
            {r.answerText && (
              <p style={{ fontSize: 12.5, color: "var(--text-muted)", background: "#f8fafc", borderRadius: 8, padding: "8px 10px", marginBottom: 10, fontStyle: "italic" }}>
                "{r.answerText}"
              </p>
            )}
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {r.feedback.map((f, fi) => (
                <span key={fi} style={{ display: "flex", alignItems: "flex-start", gap: 6, fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 }}>
                  <CheckCircle2 size={13} color="var(--brand-600)" style={{ marginTop: 2, flexShrink: 0 }} /> {f}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
